### ISSUE TITLE
Lab 02L03, az140-dc-vm11 is only valid if one takes the AD DS track

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#12]
# Module: 2
#### Step: 2

az140-dc-vm11 is only valid if one takes the AD DS track. For AAD DS track, the lab 01L01 created VM: az140-cl-vm11a

We either need to split lab 02L03 into two sets of instructions, or use the same VM name in lab 01L01 for both AADDS and ADDS.

Does this issue apply to all subsequent labs?

**Comment by polichtm** [comment]
That's by design. The Azure AD DS and AD DS "tracks" are not equivalent - that would effectively duplicate the number of labs.
We can provide more clarity regarding this intend if needed. Any suggestions are welcomed
rgds
Marcin

**Comment by ningweinw** [comment]
For better clarity, can we group AADDS labs and ADDS labs in two different folders?

**Comment by TesterTesterson1004** [comment]
As a clarifying question (with the caveat I have not taken these labs yet) I am trying to understand the '2-track' approach here - it is not a format I have seen any other MOC courses use and thus it seems a bit confusing.  

In a cursory reading of the Instructors Guide I'm not seeing much that expounds on the usage of the 2 tracks - is it intended that a Student will redeem an Azure Pass for the 'Active Directory Domain Services (AD DS)' Track, and then a second fresh AP so they can run cleanly through the 2nd 'Azure Active Directory Domain Services (Azure AD DS)' Track?  

If a student uses a single AP, is there anything that needs to be 'cleaned up' between working through the 2 Tracks, or can they simply delete the resource groups used when running through the first Track, before running through the 2nd Track?

**Comment by polichtm** [comment]
In general, we follow the approach in which each lab is an independent unit. Unfortunately this is not feasible in this case due to dependencies on the identity components (AD DS and Azure AD DS), which take a significant amount of time to set up. This led to the decision to create two separate tracks. 
Unfortunately creating the equivalent set of labs for each would considerably increase development and maintenance efforts, hence the unequal distribution of labs between the two tracks. The choice of AD DS was driven primarily by its prevalence and the cost of Azure AD DS (relatively higher comparing with AD DS running on an Azure VM).
If the intention is to run labs in both tracks, then the identity provider related dependencies should be removed first. This means deprovisioning Azure AD DS or deprovisioning Azure AD Connect before the other track is attempted.
Hope this makes sense - pls let me know if any additional clarification is needed
rgds
Marcin

**Comment by TesterTesterson1004** [comment]
Thanks, that definitely helps clarify my question!

**Comment by davemct** [comment]
First, this is an excellent course, Marcin.  I guess the question I'm still seeing on the labs is what to decide on the decision tree to do one track or the other.  One of the most constraining factors we have as MCTs is to manage course timing. The AADS track takes a couple more hours than the other.  The ADDS track has 6 more labs than the AADDS track totaling 245 minutes of extra lab time.   

I think most MCTs will choose the quicker track than the longer.  If this is the case, what is missed if anything, by students participating in the AADDS track?  My desire would be to let the students take the track that teaches them more fully.  That is not discussed in the course or the trainer prep guide.    I'm reviewing the labs now.

**Comment by polichtm** [comment]
Hi Dave,
appreciate the compliment. 
The intention was to find the optimal balance between the existing AVD (or rather what was WVD at the time) requirements/constraints (two authentication models that are time-consuming to set up) and the educational benefits for those who participate in the training. In addition, it was necessary to take into account the amount of time and effort involved in authoring and maintaining the course.
Pls note that each lab includes the list of dependencies. You also don't have to complete every single preceding labs in overwhelming majority of cases. At the same time, we do realize that having these dependencies is not ideal, so any suggestions regarding improving the current labs are welcome.
rgds
Marcin

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by polichtm** [comment]
Pls note that this is by design. 
Future updates to the course will take this into consideration
rgds
Marcin
