### ISSUE TITLE
Module 1: Unable to complete VM deployment

### ISSUE THREAD

**Issue by sehrish777** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#177]
# Module: 1
#### Step: 3

Description of issue
Unable to complete VM deployment. 
The error is joining the domain. I could not find a fix for this yet and followed every step properly but this error is occurring. There are some other people in my team who are facing this error using different credentials. 
Can someone please assist in fixing? I appreciate any help. 
Many Thanks!
![image](https://user-images.githubusercontent.com/52242119/158694751-5fdaf2d1-30b0-4cf8-9693-d794c8322f5d.png)

**Comment by kramit** [comment]
Look inside that param json

you will find this

    "domainUsername": {
      "value": "aadadmin1"
    },
    "domainPassword": {
      "value": "Pa55w.rd1234"
    }

your azuread account for aadadmin1 needs to have the same password of "Pa55w.rd1234" otherwise this domain join will fail.

You can fix it by changing the password for your azuread aadadmin1 account to Pa55w.ard1234 and then logging into this vma and doing a manual domain join. 

Either that or its the DNS issue 

az140-cl-vm11a deployment error of domain join not working, the DNS fix has not been applied on the AADDS console per Task 3, go back to AADDS console, follow Task 3, fix the DNS using the auto diagnostic, reboot or re-deploy az140-cl-vm11a, rejoin to adatum.com

**Comment by polichtm** [comment]
closing due to lack of response
