### ISSUE TITLE
Lab 04L02 vCPU quota insufficient for this lab

### ISSUE THREAD

**Issue by ningweinw** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#31]
# Module: 4
#### Step: 2

VM creation hits the quota limit error. If a user follows through all the labs, there will be 10 Dsv3 VMs (20 vCPUs) by now. Please increase the quota set in the first lab, or delete some VMs

**Comment by polichtm** [comment]
As per Exercise 0, task 1, step 7 of LAB_01L01_Prepare_for_deployment_of_AVD_ADDS.md

Review the output of the command executed in the previous step and ensure that you have at least 20 available vCPUs in both the Standard DSv3 Family and StandardBSFamily of Azure VMs in the target Azure region. If that's already the case, proceed directly to the next exercise. Otherwise, proceed to the next task of this exercise.

rgds
Marcin
