### ISSUE TITLE
Module 1/Ex 2/Task 3

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-140-Configuring-and-Operating-Microsoft-Azure-Virtual-Desktop#42]
# Module: 01
#### Step: 02 and 03

In Module 1, Lab (LAB_01L01_Prepare_for_deployment_of_AVD_AADDS), Exercise 2, task 3, either delete step 2 or step 3 to avoid duplication. Thanks

**Comment by polichtm** [comment]
Would you min d clarifying why you consider these two steps to be duplicates?
Here is the current content:
2. In the Azure portal, open a PowerShell session in the Cloud Shell.
3. When prompted to select either Bash or PowerShell, select PowerShell.
Note: Since this is the first time you are starting Cloud Shell by using the aadadmin1 user account, you will need to configure its Cloud Shell home directory. When presented with the You have no storage mounted message, select the subscription you are using in this lab, and select Create storage.

rgds
Marcin

**Comment by azharkhuwaja** [comment]
If you already have opened a PowerShell session in step 2, why you have to decide between bash and power shell in step 3.

Thanks
________________________________

**Comment by polichtm** [comment]
I see where the confusion might be coming from. Updated step 2...
rgds
Marcin
